Techno-Fractals/techno_fractals/accounts/urls.py
from django.urls import path
from accounts import views

urlpatterns = [
    
    path('register/',views.register,name='register'),
    path('user_login/',views.user_login,name='user_login'),
    path('about/',views.about,name='about'),
    path('',views.BlogListView.as_view(),name='blog_list'),
    path(r'^blog/(?P<pk>\d+)$/',views.BlogDetailView.as_view(),name='blog_detail'),
    path('blog/create/',views.CreateBlogView.as_view(),name='blog_create'),
    path(r'^blog/(?P<pk>\d+)/update$/',views.UpdateBlogView.as_view(),name='blog_update'),
    path(r'^blog/(?P<pk>\d+)/delete$/',views.DeleteBlogView.as_view(),name='blog_delete'),
    path('/index/', views.IndexView.as_view(),name='index'),
    path(r'^blog/(?P<pk>\d+)/publish$',views.blog_publish,name='blog_publish'),
]

app_name = 'accounts'

Techno-Fractals/techno_fractals/techno_fractals/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', views.IndexView.as_view(),name='index'),
    path('logout/',views.user_logout,name='logout'),
]

Techno-Fractals/techno_fractals/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class UserProfileInfo (models.Model):

    user = models.OneToOneField(User,on_delete=models.DO_NOTHING)
    firstname = models.CharField(max_length=256, blank=True)
    lastname = models.CharField(max_length=256, blank=True)
    picture = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username
    
class Blog(models.Model):

    writer = models.ForeignKey(User,on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=50,blank=False)
    text = models.TextField(blank=False)
    create_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('accounts:blog_detail',kwargs={'pk':self.pk})

    def publish(self):
        self.create_date = timezone.now()
        self.save()
    

Techno-Fractals/techno_fractals/accounts/forms.py
from django import forms
from accounts.models import UserProfileInfo,Blog
from django.contrib.auth.models import User

class UserProfileInfoForm(forms.ModelForm):
    firstname = forms.CharField(max_length=256,required=False)
    lastname = forms.CharField(max_length=256,required=False)
    picture = forms.ImageField(required=False)
    class Meta():
        model = UserProfileInfo
        exclude = ('user',)

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username','email','password')
       
class BlogForm(forms.ModelForm):

    class Meta():
        model = Blog
        fields = ('writer','title','text')
        widgets = {
            'title' : forms.TextInput(attrs={'class' : 'blog_form_title'}),
            'text' : forms.Textarea(attrs={'rows': 10,'cols': 60,'class' : 'blog_form_text'}) 
        }

Techno-Fractals/techno_fractals/accounts/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views.generic import (TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView)
from accounts.forms import UserForm,UserProfileInfoForm,BlogForm
from django.urls import reverse,reverse_lazy
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout
from accounts.models import UserProfileInfo,Blog
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class IndexView(TemplateView):
    template_name = 'accounts/blog_list.html'

def index(request):
    return render(request,'accounts/blog_list.html')

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            
            profile.save()
            registered = True

            return render(request,'accounts/login.html',{})

        else:
            print(user_form.errors,profile_form.errors)
    
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'accounts/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
                #return render(request,'accounts/blog_list.html',{})
            else:
                return HttpResponse('Please Login First')
        else:
            print('Something went wrong..!!')
            return render(request,'accounts/login.html',{'message':'Invalid Credentials'})
    else:
        return render(request,'accounts/login.html',{})

def about(request):
    return render(request,'accounts/about.html')

@login_required
def user_logout(request):
    logout(request)
    return render(request,'accounts/login.html',{})

class BlogListView(ListView):
    model = Blog

    def get_queryset(self):
        return Blog.objects.filter(create_date__lte=timezone.now()).order_by('-create_date')

class BlogDetailView(DetailView):
    model = Blog

class CreateBlogView(LoginRequiredMixin,CreateView):
    login_url = '/login/'
    redirect_field_name = 'accounts/blog_detail.html'

    form_class = BlogForm


    model = Blog

class UpdateBlogView(LoginRequiredMixin,UpdateView):
    login_url = '/login/'
    redirect_field_name = 'accounts/blog_detail.html'

    form_class = BlogForm
    
    model = Blog

class DeleteBlogView(LoginRequiredMixin,DeleteView):
    model = Blog

    success_url = reverse_lazy('accounts:blog_list')

@login_required
def blog_publish(request, pk):
    blog = get_object_or_404(Blog, pk=pk)
    blog.publish()
    return redirect('blog_detail', pk=pk)

Techno-Fractals/techno_fractals/accounts/templates/accounts/about.html
{% extends 'accounts/base.html' %}


{% block head_block %}

<title>About Us</title>

{% endblock %}


{% block body_block %}

<h1 class="ss"> About Us</h1><br><br><br>

<div class="container-fluid ab">


    <div class="container-fluid">

        <span>

            <h3 class="frac">What are Fractals...!!</h3><br>

            <p class="loader"><strong><span class="spgm">Geometrically : </span></strong>It is a curve whose each part is capable of rendering the entire curve again. <br>
                <strong><span class="spgm">Philosophically : </span></strong>It is eternity present at any scale and form whatever we may do. <br> <br>

                Fractals are never ending and are infinitely complex exhibiting self similarity across human curiosities. They are created by repeating a process over and over again,
                Thus we here at <strong>Techno Fractals</strong> try to give a platform to those fractal minds to share and gain knowledge expanding their scope both vertically and horizontally.
            </p>
            <br><br>
            <h3 id="wtf">Welcome to Techno Fractals</h3>

        </span>
        
    </div>
    

</div>

<script src="../../static/js/about.js"></script>

{% endblock %}

Techno-Fractals/techno_fractals/accounts/templates/accounts/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="{% static 'js/base.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    {% block head_block %}
    
    {% endblock %}
</head>
<body>

    <div class="container-fluid">

        <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse round sticky-top">

            <a class="navbar-brand" href="{% url 'accounts:blog_list' %}">
                <img class="rounded" src="{% static 'images/tf.jpg' %}" width="30" height="30" alt="Tf">
            </a>

            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand btn btn-secondary" id='tf' href="{% url 'accounts:blog_list' %}">TECHNO FRACTALS</a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ">
                <li class="nav-item active ">
                    <a class="nav-link btn btn-danger" href="{% url 'accounts:about' %}">About Us <span class="sr-only">(current)</span></a>
                </li>
                &nbsp;
                <li class="nav-item">
                    <a class="nav-link btn btn-warning" href="{% url 'admin:index' %}">Admin</a>
                </li>
                &nbsp;

                {% if user.is_authenticated %}

                <li class="nav-item">
                    <a class="nav-link btn bab" href="{% url 'accounts:blog_create' %}">Add Blog</a>
                </li>

                &nbsp;&nbsp;&nbsp;&nbsp;

                <li id="ut" class="nav-item">
                    <span class="navbar-text ">&nbsp;&nbsp;Logged in as : {{ user.username|title }}</span>
                </li>

                <li class="nav-item navbar-toggler-right float-left">
                    <a class="nav-link btn btn-danger" href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}

                <li class="nav-item">
                    <a class="nav-link btn btn-primary" href="{% url 'accounts:register' %}">Register</a>
                </li>
                &nbsp;

                <li class="nav-item navbar-toggler-right">
                    <a class="nav-link btn btn-success" href="{% url 'accounts:user_login' %}">Login</a>
                </li>
                {% endif %}

                

                </ul>
            </div>
        </nav>

    </div>



    <div class="view">
        <div class="plane main">
            <div class="circle"></div>
            <div class="circle"></div>
            <div class="circle"></div>
            <div class="circle"></div>
            <div class="circle"></div>
            <div class="circle"></div>
        </div>
    </div>


    <div class="container-fluid">

        <section>
            <div  id='left_side'>

                <div class="container-fluid">
                    <img  id="pic" src="{% static 'images/akanshu.jpg' %}" width="250px" height="250px" alt="akanshu">
                </div>

                <br><br>
        

                <div class="float-left"><a href="https://www.linkedin.com/in/akanshu-sonkar-187703127"><i style="font-size:24px" class="fa">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&#xf0e1;&nbsp;&nbsp;</i></a></div>
                <div class="float-left"><a href="https://github.com/akanshu11121"><i style="font-size:24px" class="fa">&nbsp;&nbsp;&nbsp;&nbsp;&#xf09b;&nbsp;&nbsp;&nbsp;&nbsp;</i></a></div>
                <div class="float-left"><a href="https://www.instagram.com/ak__a.n.s.h.u/"><i style="font-size:24px" class="fa">&nbsp;&nbsp;&nbsp;&nbsp;&#xf16d;&nbsp;&nbsp;&nbsp;&nbsp;</i></a></div>
                <div class="float-left"><a href="https://twitter.com/akanshu11121"><i style="font-size:24px" class="fa">&nbsp;&nbsp;&nbsp;&nbsp;&#xf099;&nbsp;&nbsp;&nbsp;&nbsp;</i></a></div>

                
                

            <br><br><br>

                <div class="container-fluid">

                        <h1>
                            <span href="" class="typewrite loader" data-period="2000" data-type='[ "Hi, I am Akanshu Sonkar and welcome to Techno Fractals.", "Techno Fractal is a blogging site that helps you to find your interest and enrich yourself with knowledge.","We here focus to share as much as possible , enabling you to grow your knowledge both vertically and horizontally.", "I am amazed by technologies : Artificial Intelligence, Machine Learning, Computer Vision, Decentralized Applications and Django are few of them." ]'>
                                <span class="wrap"></span>
                            </span>
                        </h1>

                </div>


                <div class="container-fluid">

                    {% if user.is_authenticated %}

                    

                    {% endif %}

                </div>



            </div>
            
            <article id='right_side'>
                    <div class='container-fluid'>

                        {% block body_block %}
                
                
                        {% endblock %}
                
                    </div>
             </article>
        </section>

    </div>

    <div id="ac" class="container-fluid fixed-bottom">

        <h1>
            <span id='sec' class="typewrite" data-period="2000" data-type='[ "The sands of time slow for no man.","Be anything but not predictable.","If you are failing to prepare, you are preparing to fail.","The less you try to impress, the more impressive you are.","Without conflict there is no trust.","Honesty is natural human craving.","Learn the rules like a pro, so that you can break them like an artist.","It is a mark of an educated mind to entertain a thought without accepting it.","Certainity is the enemy of growth.","Your salary is the bribe they give you to forget your dreams." ]'>
                <span class="wrap"></span>
            </span>
        </h1>

    </div>

       
    

    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

</body>
</html>

Techno-Fractals/techno_fractals/accounts/templates/accounts/blog_confirm_delete.html
{% extends 'accounts/base.html' %}


{% block head_block %}

<title>Delete Blog</title>

{% endblock %}


{% block body_block %}

<h1 class="con ss">Delete Blog ...??</h1>


<div class="container-fluid">


    <div class="container-fluid fb">
            

    {% if user.is_authenticated %}

    
    <form method="post">
      {% csrf_token %}
      <p class="loader welcome delb">Are you sure you want to delete " {{ object|title }} " ?</p><br>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <input class='btn btn-danger' type="submit" value="Confirm" />
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      <a class='btn btn-warning' href="{% url 'accounts:blog_list' %}">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;NO&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
    
    </form>
                

   {% endif %}


    </div>


</div>


{% endblock %}

Techno-Fractals/techno_fractals/accounts/templates/accounts/blog_detail.html
{% extends 'accounts/base.html' %}


{% block head_block %}

<title>{{ blog.title|title }}</title>

{% endblock %}


{% block body_block %}

<h1 class="con ss">{{ blog.title|title }}</h1>

<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<span id="po">Published on : </span>
<span id="mes">{{ blog.create_date|date:'l,d M Y - h:m a' }}</span>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

<span class="bdw">Written by : <span id="mes">{{ blog.writer|title }}</span></span>

<div class="container-fluid">


    <div class="container-fluid fb">

        <div class="container-fluid">

             <p class="loader welcome">{{ blog.text|capfirst }}</p>

        </div>

        
    </div>

    {% ifequal blog.writer|stringformat:"s" request.user.username %}

    <div class="container-fluid">


            <div>
        
                    <a class="btn btn-danger rounded db float-left" href="{% url 'accounts:blog_delete' pk=blog.pk %}">Delete</a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <a class="btn btn-warning rounded db float-left" href="{% url 'accounts:blog_update' pk=blog.pk %}">Update</a>

                   
            </div>
           
            
        
    </div>

    {% endifequal %}

    <a class="btn btn-success rounded db float-right" href="{% url 'accounts:blog_list' %}">Back</a>


</div>




{% endblock %}

Techno-Fractals/techno_fractals/accounts/templates/accounts/blog_form.html
{% extends 'accounts/base.html' %}


{% block head_block %}

<title>Create Blog</title>

{% endblock %}


{% block body_block %}

<h1 class="con ss">Create New Blog</h1>


<br><br>

<div class="container-fluid">


        <div class="container-fluid fb">

                <form method="POST" class="post-form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="btn btn-primary" type="submit" value="Save">
                </form>
                    
            
            </div>


</div>


{% endblock %}

Techno-Fractals/techno_fractals/accounts/templates/accounts/blog_list.html
{% extends 'accounts/base.html' %}


{% block head_block %}

<title>Techno Fractals</title>


{% endblock %}


{% block body_block %}


{% if user.is_authenticated %}
<h1 class="con ss">Welcome {{ user.username|title }} ...!!</h1>
{% else %}
<h1 class="con ss">Hello Fractals ...!!</h1>
{% endif %}
<br><br>


<div class="container-fluid">

    {% csrf_token %}
    {% if user.is_authenticated %}

            {% for blog in blog_list %}
                    
                <div class="container-fluid bl">
                        
                        <div class="container-fluid float-left">

                            <a href="{% url 'accounts:blog_detail' pk=blog.pk %}"><span class="btit loader">{{ blog.title }}</span></a>

                        </div>
                        <div class="container-fluid">
                            <span class="bw">by : {{ blog.writer|title }}</span>
                        </div>
                       
                </div>    


            {% endfor %}

        {% else %}

        <br>
        
           

                    <div class="container-fluid fb">

                        <h2 class="frac">Welcome Here</h2>

                        <br><br>

                        <p class="loader welcome">

                            <span id="qt" ><strong> 
                                    " It is said that in this world of chaos knowledge shows us the true path. "
                                </strong></span>
                            <br><br>

                                And ..., what's better than learning by sharing. We here at <strong>Techno Fractals</strong>
                                 provide you all a great platform to learn and grow through sharing.
                                
                                <br><br>

                                I welcome you all to our convergence and look forward to a
                                 beautiful and learning experience forever. May you cherish every 
                                 moment of your reading always and create beautiful blogs.
                            

                        </p>

                        <br><br>
                        <h3 id="wtf">Please Login To Continue</h3>

                    </div>
        


               


    {% endif %}


</div>


{% endblock %}

Techno-Fractals/techno_fractals/accounts/templates/accounts/index.html
{% extends 'accounts/base.html' %}


{% block head_block %}

<title>Techno Fractals</title>

{% endblock %}


{% block body_block %}

<h1 class="con ss">Hello Fractals ...!!</h1>


<div class="container-fluid">


    {% if user.is_authenticated %}

            {% for blog in blog_list %}

                <div class="container"> {{ blog.title }} </div>

            {% endfor %}

    {% endif %}


</div>


{% endblock %}

Techno-Fractals/techno_fractals/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}


{% block head_block %}

<title>Login</title>

{% endblock %}


{% block body_block %}

<h1 class="ss">Login Here</h1>

<br><br>
&nbsp;&nbsp;
<span id="mes">{{ message }}</span>


<div class="container-fluid form-group fb">

        <form  class="form-contact" action="{% url 'accounts:user_login' %}" method="POST">
            {% csrf_token %}
            <label class="form-label" for="username">Username : &nbsp;</label>
            <input class="for-control" type="text" placeholder="Enter your username" name="username" required><br><br>
            <label for="password">Password : &nbsp;</label>
            <input type="password" name="password" placeholder="Enter your password" required><br><br>
            <input class="btn btn-success" type="submit" value="LOGIN">
        </form>

</div>
   
{% endblock %}

Techno-Fractals/techno_fractals/accounts/templates/accounts/registration.html
{% extends 'accounts/base.html' %}


{% block head_block %}

<title>Registration</title>

{% endblock %}


{% block body_block %}
{% if registered %}

Alredy registered

{% else %}

<h1 class="ss">Register Here</h1>

<br><br>

<div class="container-fluid fb">

    <form class="rf" enctype="multipart/format-data" method="POST"">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <br>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>
        

</div>

{% endif %}
{% endblock %}